/**
 * AUTO-GENERIERT von scripts/importiereProdukte.mts – nicht von Hand pflegen.
 * Facetten-Delta der importierten Produkte (Ergänzung zu facetten.ts).
 * Farbgruppen deterministisch aus dem verifizierten Swatch-Hex (nächster Anker
 * in FARBGRUPPE_HEX). Enthält nur tatsächlich genutzte, in der Hand-Basis noch
 * fehlende Werte.
 */
import type { Farbgruppe, Geschlecht, MaterialGruppe, Passform } from './facetten';

export const MATERIAL_GRUPPEN_GENERIERT: Record<string, MaterialGruppe[]> = {
  "100 % Bio-Baumwolle": ["bio-baumwolle","baumwolle-100"],
  "100%  zertifizierte Biobaumwolle": ["bio-baumwolle","baumwolle-100"],
  "100% Baumwolle (Ash Grey: 99% Baumwolle / 1% Polyester; Sport Grey: 90% Baumwolle / 10% Polyester; Dark Heather, Heather Cardinale, Heather Navy, Safety Green, Safety Orange, Safety Pink: 50% Baumwolle / 50% Polyester)": ["baumwolle-100","mischgewebe"],
  "100% Baumwolle (Ash Grey: 99% Baumwolle / 1% Polyester; Sport Grey: 90% Baumwolle / 10% Polyester; Dark Heather, Safety Green, Safety Orange: 50% Baumwolle / 50% Polyester)": ["baumwolle-100","mischgewebe"],
  "100% Baumwolle (Birch: 99% Baumwolle / 1% Viskose)": ["baumwolle-100"],
  "100% Baumwolle (Grey Heather: 85% Baumwolle / 15% Viskose)": ["baumwolle-100"],
  "100% Baumwolle (Grey Melange: 85% Baumwolle / 15% Viskose; Ash: 98% Baumwolle / 2% Viskose)": ["baumwolle-100"],
  "100% Baumwolle (Heather Grey: 90% Baumwolle / 10% Viskose)": ["baumwolle-100"],
  "100% Baumwolle (Light Oxford: 93% Baumwolle / 7% Polyester)": ["baumwolle-100","mischgewebe"],
  "100% Baumwolle (Light Oxford: 93% Baumwolle / 7% Viskose)": ["baumwolle-100"],
  "100% Baumwolle (Sport Grey: 85% Baumwolle / 15% Viskose)": ["baumwolle-100"],
  "100% Baumwolle (Sport Grey: 85% Baumwolle / 15% Viskose, Ash: 99% Baumwolle / 1% Viskose)": ["baumwolle-100"],
  "100% Baumwolle (Sport Grey: 90% Baumwolle / 10% Viskose), (Meta Gold: 78% Baumwolle / 12% Metallic / 10% Polyester)": ["baumwolle-100","mischgewebe"],
  "100% Baumwolle (Sports Grey: 90% Baumwolle / 10% Polyester)": ["baumwolle-100","mischgewebe"],
  "100% Bio-Baumwolle": ["bio-baumwolle","baumwolle-100"],
  "100% In Konversion Bio-Baumwolle": ["bio-baumwolle","baumwolle-100"],
  "100% In Konversion-Bio-Baumwolle (Heather Grey: 90% Bio- oder In Konversion-Bio-Baumwolle / 10% Viskose)": ["bio-baumwolle","baumwolle-100"],
  "100% In-Konversion Bio-Baumwolle": ["bio-baumwolle","baumwolle-100"],
  "100% Polyester": ["polyester"],
  "100% einlaufvorbehandelte ringgesponnenem In Konversion-Bio-Baumwolle (Heather Grey: 90% Bio- oder In Konversion-Bio-Baumwolle / 10% Viskose)": ["bio-baumwolle","baumwolle-100"],
  "100% zertifizierte Biobaumwolle": ["bio-baumwolle","baumwolle-100"],
  "100% zertifizierte In-Konversion Bio-Baumwolle (Heather Grey: 90% In Konversion-Bio gewachsene Baumwolle / 10 % Viskose)": ["bio-baumwolle","baumwolle-100"],
  "100% zertifizierte In-Konversion-Bio-Baumwolle (Heather Grey: 90% In Konversion-Bio gewachsene Baumwolle / 10 % Viskose)": ["bio-baumwolle","baumwolle-100"],
  "40% Baumwolle / 60% Polyester": ["mischgewebe"],
  "50% Baumwolle / 50% Polyester": ["mischgewebe"],
  "50% Baumwolle / 50% Polyester (Light Oxford: 53% Polyester/ 47% Baumwolle)": ["mischgewebe"],
  "65% Baumwolle / 35% Polyester": ["mischgewebe"],
  "65% Polyester / 35% Baumwolle": ["mischgewebe"],
  "65% Polyester / 35% Baumwolle (Heather Grey: 85% Baumwolle / 15% Viskose)": ["mischgewebe"],
  "70% Baumwolle / 30% Polyester": ["mischgewebe"],
  "70% Baumwolle / 30% Polyester (Athletic Heather 67% Baumwolle / 33% Polyester)": ["mischgewebe"],
  "70% Baumwolle / 30% Polyester (Heather Grey: 60% Baumwolle / 40% Polyester)": ["mischgewebe"],
  "70% Baumwolle / 30% Polyester; Heather Grey: 65% Baumwolle / 35% Polyester": ["mischgewebe"],
  "75% Baumwolle, 25% Polyester": ["mischgewebe"],
  "80% Baumwolle / 20% Polyester": ["mischgewebe"],
  "80% Baumwolle / 20% Polyester (Athletic Heather 75% Baumwolle / 25% Polyester)": ["mischgewebe"],
  "80% Baumwolle / 20% Polyester (Heather Grey: 75% Baumwolle / 21% Polyester / 4% Viskose), (Heather Mid Grey: 60% Baumwolle / 40% Polyester)": ["mischgewebe"],
  "80% Baumwolle / 20% Polyester (Heather Grey: 75% Baumwolle / 25% Polyester)": ["mischgewebe"],
  "80% Baumwolle / 20% Polyester (Heather Mid Grey, Heather Navy, Heather Asphalt, Heather Red, Heather Dark Green, Heather Royal Blue, Heather Purple: 60% Baumwolle / 40% Polyester), (Heather Grey: 92% Baumwolle / 8% Viskose)": ["mischgewebe"],
  "95% Baumwolle / 5% Elasthan (Grey Heather: 82% Baumwolle / 14% Viskose / 4% Elasthan)": ["baumwolle-100"],
};

export const PASSFORMEN_GENERIERT: Record<string, Passform> = {};

export const GESCHLECHTER_GENERIERT: Record<string, Geschlecht[]> = {};

export const FARBGRUPPEN_GENERIERT: Record<string, Farbgruppe> = {
  "00461C": "gruen",
  "005683": "blau",
  "0062AE": "blau",
  "009149": "gruen",
  "01509D": "blau",
  "051733": "schwarz",
  "101145": "blau",
  "1C3775": "blau",
  "1C9A2C": "gruen",
  "1F2532": "blau",
  "205C40": "gruen",
  "215732": "gruen",
  "293E11": "gruen",
  "2D2926": "grau",
  "393D47": "grau",
  "4B271C": "rot",
  "4F413C": "grau",
  "4F758B": "blau",
  "555B66": "grau",
  "5A6F5E": "grau",
  "747679": "grau",
  "7E8F62": "gruen",
  "888B8D": "grau",
  "89163E": "rosa",
  "8FD491": "gruen",
  "Acid Lime": "gruen",
  "Acid Yellow": "gelb",
  "Amalfi Teal": "tuerkis",
  "Anthracite": "grau",
  "Antique Cherry Red (Heather)": "rot",
  "Antique Sapphire (Heather)": "blau",
  "Apple Green": "gruen",
  "Apricot": "orange",
  "Aqua": "tuerkis",
  "Aqua Green": "tuerkis",
  "Aquatic": "tuerkis",
  "Arctic White": "weiss",
  "Army": "braun",
  "Ash (Heather)": "grau",
  "Ash Black": "schwarz",
  "Ash Grey": "grau",
  "Ash Grey (Heather)": "grau",
  "Asphalt": "grau",
  "Athletic Heather": "grau",
  "Atlantic Blue": "blau",
  "Atoll": "tuerkis",
  "Aubergine": "lila",
  "Azalea": "rosa",
  "Azure Blue": "blau",
  "B23730": "rot",
  "B8B8B8": "grau",
  "Baby Pink": "rosa",
  "Baltic Blue": "blau",
  "Bark": "rot",
  "Bear Brown": "braun",
  "Beryl Blue": "blau",
  "Black": "schwarz",
  "Black Heather": "schwarz",
  "Black Opal": "schwarz",
  "Black Pure": "schwarz",
  "Blue Dusk": "blau",
  "Blue Fog": "blau",
  "Blue Midnight": "blau",
  "Blush Blue": "blau",
  "Blush Mint": "gruen",
  "Blush Pink": "rosa",
  "Bone": "grau",
  "Bordeaux": "rosa",
  "Bright Blue": "blau",
  "Bright Lime": "gruen",
  "Bright Red": "rot",
  "Bright Royal": "blau",
  "Brilliant Orange": "orange",
  "Brown": "braun",
  "Brown Savana": "braun",
  "Burgundy Red": "rot",
  "Burnt Yellow (Mango)": "gelb",
  "CDEA80": "gruen",
  "Camo Green": "gruen",
  "Candy Pink": "rosa",
  "Carbon": "grau",
  "Cardinal Red": "rot",
  "Carolina Blue": "blau",
  "Cement": "grau",
  "Charcoal": "grau",
  "Charcoal (Heather)": "grau",
  "Charcoal (Solid)": "grau",
  "Charcoal Grey (Solid)": "grau",
  "Charcoal Melange": "grau",
  "Cherry Red": "rot",
  "Chili Gold": "gelb",
  "Chocoloate Brown": "braun",
  "City Red": "rot",
  "Classic Olive": "gruen",
  "Classic Red": "rot",
  "Cloud": "grau",
  "Cobalt": "blau",
  "Cobalt Blue": "blau",
  "Cobaltblue": "blau",
  "Cocoa": "rot",
  "College Green": "gruen",
  "Convoy Grey (Solid)": "grau",
  "Coral": "rot",
  "Cornsilk": "gelb",
  "Creamy Blue": "blau",
  "Creamy Pink": "rosa",
  "DAC9AF": "braun",
  "Daisy": "gelb",
  "Dark Cherry": "rot",
  "Dark Chocolate": "braun",
  "Dark Forest": "gruen",
  "Dark Green": "gruen",
  "Dark Grey": "grau",
  "Dark Grey Melange": "grau",
  "Dark Heather": "grau",
  "Dark Heather Grey": "grau",
  "Dark Khaki": "braun",
  "Dark Orange": "orange",
  "Dark Purple": "lila",
  "Dark Royal": "blau",
  "Dark-Melange": "grau",
  "Deep Berry": "lila",
  "Deep Black": "schwarz",
  "Deep Red": "rot",
  "Deep Royal": "blau",
  "Denim": "blau",
  "Denim Blue": "blau",
  "Desert": "braun",
  "Desert Sand": "beige",
  "Diva Blue": "blau",
  "Dusk Rose": "rosa",
  "Dusty Indigo": "blau",
  "Dusty Lilac": "lila",
  "Dusty Mint": "gruen",
  "Dusty Purple": "lila",
  "Dusty Rose": "rosa",
  "Dusty Yellow": "gelb",
  "E8E7E3": "grau",
  "EEAD1A": "orange",
  "Earthy Green": "gruen",
  "Electric Blue": "blau",
  "Electric Green (Neon)": "gruen",
  "Electric Orange (Neon)": "orange",
  "Electric Yellow (Neon)": "gelb",
  "Elephant Grey": "grau",
  "F4F4EC": "gelb",
  "F7A30A": "orange",
  "FAC511": "gelb",
  "FFFFFF": "weiss",
  "Faded Black": "schwarz",
  "Faded Brown": "braun",
  "Faded Burgundy": "rot",
  "Faded Denim": "blau",
  "Faded Khaki": "braun",
  "Faded Mustard": "gelb",
  "Faded Navy": "blau",
  "Faded Pink": "rosa",
  "Faded White": "weiss",
  "Fern Green": "gruen",
  "Fir Green": "gruen",
  "Fire Red": "rot",
  "Forest Green": "gruen",
  "Forgotten Orange": "orange",
  "French Navy": "blau",
  "Frozen Yellow": "gelb",
  "Fuchsia": "rosa",
  "Garnet": "rot",
  "Gold": "gelb",
  "Gold Yellow": "gelb",
  "Graphite (Solid)": "grau",
  "Graphite Heather": "grau",
  "Green": "gruen",
  "Grenadine": "rot",
  "Grey": "grau",
  "Grey Fog": "grau",
  "Grey Heather": "grau",
  "Grey Melange": "grau",
  "Hawaiian Blue": "blau",
  "Heather Asphalt": "grau",
  "Heather Cardinal": "grau",
  "Heather Dark Green": "gruen",
  "Heather Denim": "blau",
  "Heather Green": "gruen",
  "Heather Mid Grey": "grau",
  "Heather Navy": "blau",
  "Heather Oxblood": "grau",
  "Heather Red": "rot",
  "Heather Royal Blue": "blau",
  "Heliconia": "rosa",
  "Hellblau": "blau",
  "Hibiscus": "rosa",
  "Hibiskus Pink": "rosa",
  "Hunters Green": "gruen",
  "Ice Blue": "blau",
  "Ice Grey (Solid)": "grau",
  "Indigo": "blau",
  "Indigo Blue": "blau",
  "Ink Blue": "blau",
  "Iris": "blau",
  "Irish Green": "gruen",
  "Ivy Green": "gruen",
  "Jade Dome": "tuerkis",
  "Jade Green": "gruen",
  "Jet Black": "schwarz",
  "King Blue": "blau",
  "Kiwi": "gelb",
  "Kiwi Green": "gruen",
  "Lake Blue": "blau",
  "Lavender": "lila",
  "Light Asphalt": "grau",
  "Light Beige (Sand)": "beige",
  "Light Blue": "blau",
  "Light Charcoal": "grau",
  "Light Denim Melange": "blau",
  "Light Graphite (Solid)": "grau",
  "Light Grey": "grau",
  "Light Heather": "grau",
  "Light Jade": "gruen",
  "Light Melange": "braun",
  "Light Mint": "gruen",
  "Light Navy": "blau",
  "Light Oxford (Heather)": "grau",
  "Light Pink": "rosa",
  "Light Yellow": "gelb",
  "Lilac": "lila",
  "Lime": "gruen",
  "Linen": "braun",
  "Lotus Blue": "blau",
  "Lotus Pink": "rosa",
  "Magenta Pink": "rosa",
  "Magnet": "grau",
  "Mango": "orange",
  "Marina Blue": "blau",
  "Maroon": "rot",
  "Mastic": "braun",
  "Melange Grey": "grau",
  "Melon Orange": "orange",
  "Meta Fuchsia": "rosa",
  "Meta Gold": "gelb",
  "Meta Lilac": "lila",
  "Meta Orange": "orange",
  "Meta Turquoise": "tuerkis",
  "Metro Blue": "blau",
  "Miami Pink (Purple Rose)": "lila",
  "Military": "gruen",
  "Military Green": "gruen",
  "Millennial Khaki": "braun",
  "Millennial Mint": "gruen",
  "Millennial Pink": "rosa",
  "Mineral Blue": "blau",
  "Mint": "gruen",
  "Mint Green": "gruen",
  "Mocha": "braun",
  "Moss Green": "gruen",
  "Mouse Grey (Solid)": "grau",
  "Mustard": "gelb",
  "Natural Clay": "beige",
  "Natural Stone": "beige",
  "Nature": "gelb",
  "Navy Blue": "blau",
  "Navy Pure": "blau",
  "Neo Mint": "gruen",
  "Neon Orange": "orange",
  "Neon Yellow": "gelb",
  "New French Navy": "blau",
  "Nordic Blue": "blau",
  "Nude": "orange",
  "Ocean Blue": "blau",
  "Off White": "weiss",
  "Okay Orange": "orange",
  "Old Gold": "gelb",
  "Orchid": "lila",
  "Orchid Green": "gruen",
  "Orchid Pink": "lila",
  "Oxblood": "rot",
  "Pacific": "tuerkis",
  "Pacific Grey": "grau",
  "Pale Leaf": "tuerkis",
  "Pale Olive": "gruen",
  "Pale Pink": "rosa",
  "Pale Yellow": "gelb",
  "Paradise Orange": "orange",
  "Paragon": "grau",
  "Petrol Blue": "blau",
  "Pink Fizz": "rosa",
  "Pink Lemonade": "rosa",
  "Pistachio": "gelb",
  "Pixel Coral": "rot",
  "Pixel Lime": "gruen",
  "Plum Purple": "lila",
  "Pop Green": "gruen",
  "Pop Tomato": "rot",
  "Pop Turquoise": "tuerkis",
  "Pop Yellow": "gelb",
  "Powder Rose": "rosa",
  "Prairie Dust": "grau",
  "Pumpkin Orange": "orange",
  "Pure Grey": "grau",
  "Pure Orange": "orange",
  "Pure Sky": "tuerkis",
  "Purple Night": "lila",
  "RFD (Ready for Dye)": "grau",
  "Radiant Purple": "lila",
  "Raw": "gelb",
  "Ready To Dye": "weiss",
  "Real Green": "gruen",
  "Real Grey": "grau",
  "Real Turquoise": "tuerkis",
  "Red": "rot",
  "Retro Green": "gruen",
  "Roasted Coffee": "braun",
  "Rope": "braun",
  "Rose": "rosa",
  "Royal Blue": "blau",
  "Royal Blue 241": "blau",
  "Ruby": "rot",
  "Safety Green": "gruen",
  "Safety Green (Neon)": "gruen",
  "Safety Orange": "orange",
  "Safety Orange (Neon)": "orange",
  "Sage Green": "gruen",
  "Salmon": "rot",
  "Sapphire": "blau",
  "Sapphire Blue": "blau",
  "Scarlet Red": "rot",
  "Signal Red": "rot",
  "Sky": "blau",
  "Slate Blue": "blau",
  "Slate Grey (Solid)": "grau",
  "Smoke": "grau",
  "Soft Grey": "grau",
  "Soft Pink": "rosa",
  "Soft Rose": "rosa",
  "Soft Salvia": "gelb",
  "Soft Yellow": "gelb",
  "Solid Charcoal": "grau",
  "Sorbet": "rosa",
  "Sport Grey": "grau",
  "Sport Grey (Heather)": "grau",
  "Sport Heather": "grau",
  "Sports Grey": "grau",
  "Spring Green": "gruen",
  "Steel Grey": "grau",
  "Stone": "beige",
  "Stone Blue": "blau",
  "Stone Washed Black": "beige",
  "Stone Washed Burgundy": "rot",
  "Stone Washed Denim": "blau",
  "Stone Washed Green": "gruen",
  "Stone Washed Grey": "beige",
  "Stone Washed Pink": "rosa",
  "Stone Washed Sage Green": "gruen",
  "Stone Washed White": "beige",
  "Sueded Black": "schwarz",
  "Sueded Blue Dusk": "blau",
  "Sueded Fawn": "braun",
  "Sueded Light Blue Heather": "blau",
  "Sueded Light Heather": "grau",
  "Sueded Miami Pink": "rosa",
  "Sueded Off White": "weiss",
  "Sueded Orange": "orange",
  "Sueded Pale Lemon": "gelb",
  "Sueded Slate Green": "gruen",
  "Sunflower Yellow": "gelb",
  "Sunset Orange": "orange",
  "Sweet Pink": "rosa",
  "Swimming Pool": "tuerkis",
  "T. Orange": "orange",
  "Tan": "beige",
  "Tangerine": "orange",
  "Taxi Yellow": "gelb",
  "Teal": "tuerkis",
  "Texas Orange": "orange",
  "Titanium (Solid)": "blau",
  "Tomato": "rot",
  "Turquoise": "tuerkis",
  "U. Beige": "beige",
  "Ultraviolett": "lila",
  "Union Beige": "beige",
  "Urban Black": "schwarz",
  "Urban Grey": "grau",
  "Urban Navy": "blau",
  "Urban Orange": "orange",
  "Urban Purple": "lila",
  "Used Black": "schwarz",
  "Vanilla": "weiss",
  "Vegas Gold": "gelb",
  "Vintage Blue": "blau",
  "Violet": "lila",
  "White": "weiss",
  "White - Navy (Striped)": "blau",
  "White Sand": "beige",
  "Wine": "rot",
  "Yellow Fizz": "gelb",
  "Yellow Haze": "gelb",
};
