import { computeBasePrice } from '@/config/pricing/marginTiers';
import { realPhotoColorSet } from './colorHelpers';
import type { ProductConfig } from './types';

/**
 * Fruit of the Loom – erste externe Marke im Katalog (siehe
 * products/index.ts für das Registrierungs-Rezept künftiger Marken).
 *
 * Anders als bei ownCollection.ts ist "anchorColorId" hier reine Ordner-
 * Namenskonvention: JEDE Farbe hat ein echtes eigenes Foto (keine HSL-
 * Rekolorierung), siehe Kommentar in colorHelpers.ts.
 *
 * purchasePrice-Werte sind PLATZHALTER (Quell-Datenblätter enthalten
 * keine Einkaufspreise) – echte Zahlen liefert der Nutzer später nach.
 */

const HEAVY_T_PURCHASE_PRICE = 4.2; // PLATZHALTER – echter EK-Preis noch unbekannt
const LADIES_VALUEWEIGHT_VNECK_PURCHASE_PRICE = 2.6; // PLATZHALTER
const ORIGINAL_LONGSLEEVE_PURCHASE_PRICE = 5.8; // PLATZHALTER
const ORIGINAL_VNECK_PURCHASE_PRICE = 3.8; // PLATZHALTER
const LADIES_ORIGINAL_T_PURCHASE_PRICE = 3.6; // PLATZHALTER
const ICONIC_195_LONGSLEEVE_PURCHASE_PRICE = 6.8; // PLATZHALTER
const PURE_COTTON_T_PURCHASE_PRICE = 3.4; // PLATZHALTER
const SUPER_PREMIUM_T_PURCHASE_PRICE = 5.4; // PLATZHALTER
const VALUEWEIGHT_T_PURCHASE_PRICE = 2.5; // PLATZHALTER
const VALUEWEIGHT_VNECK_PURCHASE_PRICE = 2.6; // PLATZHALTER
const ICONIC_195_T_PURCHASE_PRICE = 5.4; // PLATZHALTER
const LADIES_ICONIC_195_T_PURCHASE_PRICE = 5.3; // PLATZHALTER
const ORIGINAL_T_PURCHASE_PRICE = 3.2; // PLATZHALTER
const LADIES_VALUEWEIGHT_T_PURCHASE_PRICE = 2.5; // PLATZHALTER
const BASEBALL_T_PURCHASE_PRICE = 4.84; // ab-Preis textil-grosshandel.eu (Artikel F295)
const PREMIUM_POLO_PURCHASE_PRICE = 7.62; // ab-Preis textil-grosshandel.eu (Artikel F511N)
const BASEBALL_LONGSLEEVE_PURCHASE_PRICE = 5.51; // ab-Preis textil-grosshandel.eu (Artikel F296)
const LADIES_PREMIUM_POLO_PURCHASE_PRICE = 7.8; // ab-Preis textil-grosshandel.eu (Artikel F520)

export const PRODUCTS: ProductConfig[] = [
  {
    id: 'fotl-heavy-t',
    name: 'Heavy T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'standard',
    purchasePrice: HEAVY_T_PURCHASE_PRICE,
    basePrice: computeBasePrice(HEAVY_T_PURCHASE_PRICE, 'standard'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    tagline: 'Schwere Baumwolle, leicht im Preis',
    material: '100% Baumwolle (meliert: 98% Baumwolle, 2% Polyester)',
    weightGsm: 195,
    fit: 'Classic Fit, Unisex',
    description:
      'Schwere Baumwolle, leicht im Preis. Das einfarbige T-Shirt steht für hohe Qualität und Langlebigkeit in einem fairen Paket. Es ist aus 100% Baumwolle mit dichtem, flachem Griff und einer modernen, etwas raueren Textur gefertigt und eine beliebte Wahl für Workwear und Musik-Merchandising. Dank einem extrahohen Stoffgewicht (185–195g/m²) und der griffigen Textur behält es auch bei häufigem Waschen und Tragen alle seine positiven Eigenschaften.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Unisex/Herren',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: '100% Baumwolle, grobmaschiges Offen-End-Garn (22gg)',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'Rundhalsausschnitt',
        'Klassische Passform',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 46, hoeheCm: 68.5 },
        { size: 'M', breiteCm: 51, hoeheCm: 71 },
        { size: 'L', breiteCm: 56, hoeheCm: 73.5 },
        { size: 'XL', breiteCm: 61, hoeheCm: 76 },
        { size: 'XXL', breiteCm: 66, hoeheCm: 77.5 },
        { size: '3XL', breiteCm: 71, hoeheCm: 79 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-heavy-t', 'white', ['navy', 'black', 'heather-grey']),
  },
  {
    id: 'fotl-ladies-valueweight-vneck',
    name: 'Ladies Valueweight V-Neck T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'basic',
    purchasePrice: LADIES_VALUEWEIGHT_VNECK_PURCHASE_PRICE,
    basePrice: computeBasePrice(LADIES_VALUEWEIGHT_VNECK_PURCHASE_PRICE, 'basic'),
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    tagline: 'Leichtes Damen-T-Shirt mit V-Ausschnitt',
    material: '100% Baumwolle (meliert: Baumwoll-/Polyester-Mischgewebe)',
    weightGsm: 165,
    fit: 'Feminine Passform mit Seitennähten',
    description: 'Leichtes Damen-T-Shirt mit V-Ausschnitt, gleichfarbigem Nackenband und femininer Passform.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Damen',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Höhere Maschendichte für bessere Bedruckbarkeit',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'V-Ausschnitt',
        'Gleichfarbiges Nackenband',
        'Feminine Passform mit Seitennähten',
        'Höhere Maschendichte für bessere Bedruckbarkeit',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    // Vierte Farbe (Navy) im Rohmaterial nur mit Front-/Rückansicht
    // vorhanden (keine Seitenansicht) – bewusst ausgelassen statt eine
    // fehlende Aufnahme zu erraten; kann nachgezogen werden, sobald ein
    // vollständiger Foto-Satz vorliegt.
    sizeGuide: {
      measurements: [
        { size: 'XS', breiteCm: 41.5, hoeheCm: 62 },
        { size: 'S', breiteCm: 44, hoeheCm: 63 },
        { size: 'M', breiteCm: 46.5, hoeheCm: 64 },
        { size: 'L', breiteCm: 49, hoeheCm: 65 },
        { size: 'XL', breiteCm: 51.5, hoeheCm: 66 },
        { size: 'XXL', breiteCm: 54, hoeheCm: 67 },
      ],
      fitRating: 50,
    },
    // Vierte Farbe (Navy) im Rohmaterial nur mit Front-/Rückansicht
    // vorhanden (keine Seitenansicht) – bewusst ausgelassen statt eine
    // fehlende Aufnahme zu erraten; kann nachgezogen werden, sobald ein
    // vollständiger Foto-Satz vorliegt.
    colors: realPhotoColorSet('fotl-ladies-vneck', 'black', ['white', 'heather-grey']),
  },
  {
    id: 'fotl-original-longsleeve',
    name: 'Original Long Sleeve T',
    brand: 'Fruit of the Loom',
    productType: 'longsleeve',
    qualityTier: 'standard',
    purchasePrice: ORIGINAL_LONGSLEEVE_PURCHASE_PRICE,
    basePrice: computeBasePrice(ORIGINAL_LONGSLEEVE_PURCHASE_PRICE, 'standard'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    tagline: 'Vielseitiges Longsleeve für Veredelungsprojekte',
    material: '100% Baumwolle (meliert: 98% Baumwolle, 2% Polyester)',
    weightGsm: 145,
    fit: 'Classic Fit, Unisex',
    description:
      'Das Original Long Sleeve T ist ein vielseitiges unbedrucktes Longsleeve aus 100% Baumwolle und ein komfortabler Favorit für jeden Tag. Der gerippte Rundhalsausschnitt verleiht dem Essential zusätzlich Qualität und die feinmaschige Konstruktion sorgt für besonders gute Bedruckbarkeit. Mit seinem Classic Fit überzeugt es solo und als Layering Piece gleichermaßen.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'Longsleeves',
      gender: 'Unisex/Herren',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Höhere Maschendichte für bessere Bedruckbarkeit',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'Rundhalsausschnitt',
        'Höhere Maschendichte für bessere Bedruckbarkeit',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 46, hoeheCm: 66.5 },
        { size: 'M', breiteCm: 51, hoeheCm: 69 },
        { size: 'L', breiteCm: 56, hoeheCm: 71.5 },
        { size: 'XL', breiteCm: 61, hoeheCm: 74 },
        { size: 'XXL', breiteCm: 66, hoeheCm: 76.5 },
        { size: '3XL', breiteCm: 73, hoeheCm: 79 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-original-longsleeve', 'black', ['white']),
  },
  {
    id: 'fotl-original-vneck',
    name: 'Original V-Neck T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'standard',
    purchasePrice: ORIGINAL_VNECK_PURCHASE_PRICE,
    basePrice: computeBasePrice(ORIGINAL_VNECK_PURCHASE_PRICE, 'standard'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tagline: 'Bestseller mit V-Ausschnitt',
    material: '100% Baumwolle (meliert: 98% Baumwolle, 2% Polyester)',
    weightGsm: 145,
    fit: 'Classic Fit, Unisex',
    description: 'Unbedrucktes T-Shirt mit V-Ausschnitt und gleichfarbigem Nackenband, feinmaschig für gute Bedruckbarkeit.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Unisex/Herren',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Höhere Maschendichte für bessere Bedruckbarkeit',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'V-Ausschnitt',
        'Gleichfarbiges Nackenband',
        'Höhere Maschendichte für bessere Bedruckbarkeit',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 46, hoeheCm: 66.5 },
        { size: 'M', breiteCm: 51, hoeheCm: 69 },
        { size: 'L', breiteCm: 56, hoeheCm: 71.5 },
        { size: 'XL', breiteCm: 61, hoeheCm: 74 },
        { size: 'XXL', breiteCm: 66, hoeheCm: 76.5 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-original-vneck', 'black', ['white']),
  },
  {
    id: 'fotl-ladies-original-t',
    name: 'Ladies Original T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'standard',
    purchasePrice: LADIES_ORIGINAL_T_PURCHASE_PRICE,
    basePrice: computeBasePrice(LADIES_ORIGINAL_T_PURCHASE_PRICE, 'standard'),
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    tagline: 'Unbedruckter Damen-Bestseller in Feminine Fit',
    material: '100% Baumwolle (meliert: 98% Baumwolle, 2% Polyester)',
    weightGsm: 165,
    fit: 'Feminine Fit mit Seitennähten',
    description:
      'Die Damen-Variante unseres unbedruckten T-Shirt-Bestsellers kommt im Feminine Fit. Das T-Shirt aus 100% Baumwolle verbindet mit seinem mittleren Stoffgewicht von 160/165g/m² ein robustes Design mit hohem Komfort für jeden Tag und einer glatten Oberfläche, die zuverlässig perfekte Print-Ergebnisse liefert.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Damen',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Höhere Maschendichte für bessere Bedruckbarkeit',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'Rundhalsausschnitt',
        'Feminine Passform mit Seitennähten',
        'Höhere Maschendichte für bessere Bedruckbarkeit',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    sizeGuide: {
      measurements: [
        { size: 'XS', breiteCm: 41.5, hoeheCm: 62 },
        { size: 'S', breiteCm: 44, hoeheCm: 63 },
        { size: 'M', breiteCm: 46.5, hoeheCm: 64 },
        { size: 'L', breiteCm: 49, hoeheCm: 65 },
        { size: 'XL', breiteCm: 51.5, hoeheCm: 66 },
        { size: 'XXL', breiteCm: 54, hoeheCm: 67 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-ladies-original-t', 'white', ['black', 'red', 'royal', 'pink', 'heather-grey']),
  },
  {
    id: 'fotl-iconic195-longsleeve',
    name: 'Iconic 195 Ringspun Premium Long Sleeve T',
    brand: 'Fruit of the Loom',
    productType: 'longsleeve',
    qualityTier: 'premium',
    purchasePrice: ICONIC_195_LONGSLEEVE_PURCHASE_PRICE,
    basePrice: computeBasePrice(ICONIC_195_LONGSLEEVE_PURCHASE_PRICE, 'premium'),
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL'],
    tagline: 'Premium-Longsleeve aus ringgesponnener Baumwolle',
    material: '100% Baumwolle (meliert: 97% Baumwolle, 3% Polyester)',
    weightGsm: 195,
    fit: 'Classic Fit, Unisex',
    description:
      'Premium-Longsleeve aus 100% ringgesponnener Baumwolle, das luxuriöse Weichheit mit einer Extraportion Robustheit verbindet. Mit einem Stoffgewicht von 190g/m² in Weiß und 195g/m² für die farbigen Varianten eignet es sich ideal zum täglichen Tragen und liefert außergewöhnliche Print-Ergebnisse.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '60°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'Longsleeves',
      gender: 'Unisex/Herren',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: '100% gekämmte, ringgesponnene Baumwolle',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        '100% gekämmte, ringgesponnene Baumwolle',
        'Weicher Griff',
        'Waschbar bei 60 Grad',
        'Rundhalsausschnitt',
        'Durchgehendes Nackenband von Schulter zu Schulter',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    // Vierte Farbe (Royal) im Rohmaterial nur mit Front-/Rückansicht
    // vorhanden (keine Seitenansicht) – bewusst ausgelassen, siehe
    // Heavy-T-Kommentar zum selben Muster.
    sizeGuide: {
      measurements: [
        { size: 'XS', breiteCm: 46, hoeheCm: 67 },
        { size: 'S', breiteCm: 48.5, hoeheCm: 69.5 },
        { size: 'M', breiteCm: 53.5, hoeheCm: 72 },
        { size: 'L', breiteCm: 56, hoeheCm: 74.5 },
        { size: 'XL', breiteCm: 61, hoeheCm: 77 },
        { size: 'XXL', breiteCm: 66, hoeheCm: 78.5 },
        { size: '3XL', breiteCm: 71, hoeheCm: 80 },
        { size: '4XL', breiteCm: 76, hoeheCm: 81.5 },
        { size: '5XL', breiteCm: 81, hoeheCm: 83 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-iconic195-longsleeve', 'black', ['white', 'red', 'heather-grey', 'navy']),
  },
  {
    id: 'fotl-pure-cotton-t',
    name: 'Pure Cotton T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'basic',
    purchasePrice: PURE_COTTON_T_PURCHASE_PRICE,
    basePrice: computeBasePrice(PURE_COTTON_T_PURCHASE_PRICE, 'basic'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    tagline: 'Umweltbewusstes T-Shirt aus Bio-Baumwolle',
    material: '100% gekämmte, ringgesponnene Bio-Baumwolle',
    weightGsm: 180,
    fit: 'Classic Fit, Unisex',
    description:
      'Aus 100% gekämmter, ringgesponnener Bio-Baumwolle gefertigt und das perfekte umweltbewusste T-Shirt für alle Arten der Textilveredelung.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Unisex/Herren',
      sustainability: 'Bio-Baumwolle, plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: '1x1 Rippstrick-Kragen mit einfacher Steppnaht',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'Klassische Passform',
        'Rundhals',
        '1x1 Rippstrick-Kragen mit einfacher Steppnaht',
        'Schulter-zu-Schulter-Nackenband',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    // Größentabelle: echte Werte für Pure Cotton T waren beim Lieferanten
    // nur als Bild-Grafik hinterlegt (nicht als Text abrufbar) – als
    // Näherung wird stattdessen die Tabelle von Heavy T übernommen (gleiche
    // Passform-Klasse, ähnliches Gewicht).
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 46, hoeheCm: 68.5 },
        { size: 'M', breiteCm: 51, hoeheCm: 71 },
        { size: 'L', breiteCm: 56, hoeheCm: 73.5 },
        { size: 'XL', breiteCm: 61, hoeheCm: 76 },
        { size: 'XXL', breiteCm: 66, hoeheCm: 77.5 },
        { size: '3XL', breiteCm: 71, hoeheCm: 79 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-pure-cotton-t', 'black', [
      'white',
      'red',
      'royal',
      'sage',
      'navy',
      'sand',
      'grey',
          'petrol',
      'sky-blue',
      'very-turquoise',
]),
  },
  {
    id: 'fotl-super-premium-t',
    name: 'Super Premium T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'premium',
    purchasePrice: SUPER_PREMIUM_T_PURCHASE_PRICE,
    basePrice: computeBasePrice(SUPER_PREMIUM_T_PURCHASE_PRICE, 'premium'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL'],
    tagline: 'Der Branchenliebling unter den Premium-T-Shirts',
    material: '100% Baumwolle (meliert: 98-99% Baumwolle, 1-2% Polyester)',
    weightGsm: 205,
    fit: 'Classic Fit, Unisex',
    description:
      'Unser Super Premium T trägt nicht umsonst das Wort "Premium" in seinem Namen. Aus 100% schwerer Baumwolle mit modern texturiertem Griff gefertigt, mit grobmaschigem Open-End-Garn (24gg) und einem Stoffgewicht von 190/205g/m² – die erste Wahl für Textilveredelung.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '60°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Unisex/Herren',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Grobmaschiges Open-End-Garn (24gg)',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'Waschbar bis 60°C',
        'Rundhalsausschnitt',
        'Gleichfarbiges Nackenband',
        'Höhere Maschendichte für bessere Bedruckbarkeit',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    // Weiß im Rohmaterial nur mit einer einzigen Aufnahme vorhanden (kein
    // Rück-/Seitenfoto) – bewusst ausgelassen, siehe Muster bei anderen
    // Produkten dieser Marke.
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 48.5, hoeheCm: 69.5 },
        { size: 'M', breiteCm: 53.5, hoeheCm: 72 },
        { size: 'L', breiteCm: 56, hoeheCm: 74.5 },
        { size: 'XL', breiteCm: 61, hoeheCm: 77 },
        { size: 'XXL', breiteCm: 66, hoeheCm: 78.5 },
        { size: '3XL', breiteCm: 71, hoeheCm: 80 },
        { size: '4XL', breiteCm: 76, hoeheCm: 81.5 },
        { size: '5XL', breiteCm: 81, hoeheCm: 83 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-super-premium-t', 'navy', [
      'black',
      'bottle-green',
      'red',
      'royal',
      'olive',
      'heather-grey',
      'graphite',
          'dark-grey-solid',
]),
  },
  {
    id: 'fotl-valueweight-t',
    name: 'Valueweight T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'basic',
    purchasePrice: VALUEWEIGHT_T_PURCHASE_PRICE,
    basePrice: computeBasePrice(VALUEWEIGHT_T_PURCHASE_PRICE, 'basic'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL'],
    tagline: 'Der Bestseller unter den unbedruckten T-Shirts',
    material: '100% Baumwolle (meliert: diverse Baumwoll-/Polyester-Mischungen)',
    weightGsm: 165,
    fit: 'Classic Fit, Unisex',
    description:
      'Das Valueweight T ist unser Bestseller. Das hochwertige unbedruckte T-Shirt aus 100% Baumwolle ist mit einem mittleren Stoffgewicht von 160/165 g/m² ein vielseitiger Allrounder für jeden Tag und kombiniert hohen Tragekomfort mit einer glatten Oberfläche, die sich perfekt zur Textilveredelung eignet.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Unisex/Herren',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Höhere Maschendichte für bessere Bedruckbarkeit',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'Rundhalsausschnitt',
        'Gleichfarbiges Nackenband',
        'Höhere Maschendichte für bessere Bedruckbarkeit',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    // Black (nur 2 Fotos, keine Seitenansicht) und Lime Green (ebenfalls
    // nur 2 Fotos) im Rohmaterial unvollständig – bewusst ausgelassen,
    // siehe Muster bei anderen Produkten dieser Marke.
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 48.5, hoeheCm: 69.5 },
        { size: 'M', breiteCm: 53.5, hoeheCm: 72 },
        { size: 'L', breiteCm: 56, hoeheCm: 74.5 },
        { size: 'XL', breiteCm: 61, hoeheCm: 76 },
        { size: 'XXL', breiteCm: 66, hoeheCm: 77.5 },
        { size: '3XL', breiteCm: 71, hoeheCm: 79 },
        { size: '4XL', breiteCm: 76, hoeheCm: 80.5 },
        { size: '5XL', breiteCm: 81, hoeheCm: 82 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-valueweight-t', 'white', [
      'navy',
      'bottle-green',
      'red',
      'burgundy',
      'royal',
      'pink',
      'olive',
      'natural',
      'heather-grey',
      'graphite',
      'solar-yellow',
      'azure',
          'brick-red',
      'chocolate',
      'heather-royal',
      'purple',
      'sunflower',
]),
  },
  {
    id: 'fotl-valueweight-vneck',
    name: 'Valueweight V-Neck T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'basic',
    purchasePrice: VALUEWEIGHT_VNECK_PURCHASE_PRICE,
    basePrice: computeBasePrice(VALUEWEIGHT_VNECK_PURCHASE_PRICE, 'basic'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL'],
    tagline: 'Der Bestseller mit V-Ausschnitt',
    material: '100% Baumwolle (meliert: diverse Baumwoll-/Polyester-Mischungen)',
    weightGsm: 165,
    fit: 'Classic Fit, Unisex',
    description: 'Unbedrucktes T-Shirt mit V-Ausschnitt und gleichfarbigem Nackenband, feinmaschig für gute Bedruckbarkeit.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Unisex/Herren',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Höhere Maschendichte für bessere Bedruckbarkeit',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'V-Ausschnitt',
        'Gleichfarbiges Nackenband',
        'Höhere Maschendichte für bessere Bedruckbarkeit',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 45.5, hoeheCm: 69.5 },
        { size: 'M', breiteCm: 48.5, hoeheCm: 72 },
        { size: 'L', breiteCm: 53.5, hoeheCm: 74.5 },
        { size: 'XL', breiteCm: 58.5, hoeheCm: 77 },
        { size: 'XXL', breiteCm: 63.5, hoeheCm: 78.5 },
        { size: '3XL', breiteCm: 68.5, hoeheCm: 80 },
        { size: '4XL', breiteCm: 73.5, hoeheCm: 81.5 },
        { size: '5XL', breiteCm: 78.5, hoeheCm: 83 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-valueweight-vneck', 'white', [
      'navy',
      'solar-yellow',
      'black',
      'red',
      'orange',
      'royal',
      'heather-grey',
      'deep-navy',
      'graphite',
      'azure',
          'heather-charcoal',
]),
  },
  {
    id: 'fotl-iconic195-t',
    name: 'Iconic 195 Ringspun Premium T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'premium',
    purchasePrice: ICONIC_195_T_PURCHASE_PRICE,
    basePrice: computeBasePrice(ICONIC_195_T_PURCHASE_PRICE, 'premium'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL'],
    tagline: 'Premium-T-Shirt aus ringgesponnener Baumwolle',
    material: '100% Baumwolle (meliert: 97-99% Baumwolle, 1-3% Polyester)',
    weightGsm: 195,
    fit: 'Classic Fit, Unisex',
    description:
      'Das Iconic 195 Ringspun Premium T ist unser Premium-T-Shirt aus 100% ringgesponnener Baumwolle, das luxuriöse Weichheit mit einer Extraportion Robustheit verbindet. Mit einem Stoffgewicht von 190g/m² in Weiß und 195g/m² für die farbigen Varianten eignet es sich ideal zum täglichen Tragen und liefert außergewöhnliche Druckergebnisse.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '60°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Unisex/Herren',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: '100% gekämmte, ringgesponnene Baumwolle',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        '100% gekämmte, ringgesponnene Baumwolle',
        'Weicher Griff',
        'Waschbar bei 60 Grad',
        'Rundhalsausschnitt',
        'Durchgehendes Nackenband von Schulter zu Schulter',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    // Größentabelle: die vom Lieferanten verlinkte Seite für Iconic 195 T
    // führte fälschlich zur Longsleeve-Variante (Datenfehler im
    // Quell-Datenblatt) bzw. lieferte 404 – als Näherung wird die Tabelle
    // der gewichtsgleichen Iconic 195 Longsleeve/Super Premium T
    // übernommen (identische Werte bei beiden Referenzen).
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 48.5, hoeheCm: 69.5 },
        { size: 'M', breiteCm: 53.5, hoeheCm: 72 },
        { size: 'L', breiteCm: 56, hoeheCm: 74.5 },
        { size: 'XL', breiteCm: 61, hoeheCm: 77 },
        { size: 'XXL', breiteCm: 66, hoeheCm: 78.5 },
        { size: '3XL', breiteCm: 71, hoeheCm: 80 },
        { size: '4XL', breiteCm: 76, hoeheCm: 81.5 },
        { size: '5XL', breiteCm: 81, hoeheCm: 83 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-iconic195-t', 'azure', [
      'white',
      'navy',
      'solar-yellow',
      'black',
      'bottle-green',
      'red',
      'burgundy',
      'sage',
      'royal',
      'olive',
      'natural',
      'deep-navy',
      'cranberry',
      'sand',
      'graphite',
      'heather-grey',
          'khaki',
      'powder-blue',
]),
  },
  {
    id: 'fotl-ladies-iconic195-t',
    name: 'Ladies Iconic 195 Ringspun Premium T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'premium',
    purchasePrice: LADIES_ICONIC_195_T_PURCHASE_PRICE,
    basePrice: computeBasePrice(LADIES_ICONIC_195_T_PURCHASE_PRICE, 'premium'),
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    tagline: 'Premium-Damen-T-Shirt aus ringgesponnener Baumwolle',
    material: '100% Baumwolle (meliert: 97-99% Baumwolle, 1-3% Polyester)',
    weightGsm: 195,
    fit: 'Feminine Passform mit Seitennähten',
    description:
      'Das hochwertige unbedruckte T-Shirt ist aus 100% gekämmter, ringgesponnener Baumwolle mit weichem Griff gefertigt und mit Seitennähten ausgestattet, die den Feminine Fit elegant unterstreichen. Bietet die perfekte Balance aus Wertigkeit und Preis.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '60°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Damen',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: '100% gekämmte, ringgesponnene Baumwolle',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        '100% gekämmte, ringgesponnene Baumwolle',
        'Weicher Griff',
        'Feminine Passform mit Seitennähten',
        'Waschbar bei 60 Grad',
        'Durchgehendes Nackenband von Schulter zu Schulter',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    sizeGuide: {
      measurements: [
        { size: 'XS', breiteCm: 41.5, hoeheCm: 62 },
        { size: 'S', breiteCm: 44, hoeheCm: 63 },
        { size: 'M', breiteCm: 46.5, hoeheCm: 64 },
        { size: 'L', breiteCm: 49, hoeheCm: 65 },
        { size: 'XL', breiteCm: 51.5, hoeheCm: 66 },
        { size: 'XXL', breiteCm: 54, hoeheCm: 67 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-ladies-iconic195-t', 'azure', [
      'navy',
      'solar-yellow',
      'black',
      'red',
      'royal',
      'burgundy',
      'pink',
      'natural',
      'deep-navy',
      'cranberry',
      'sand',
      'graphite',
      'white',
          'blush',
      'millennial-lilac',
      'very-turquoise',
]),
  },
  {
    id: 'fotl-original-t',
    name: 'Original T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'standard',
    purchasePrice: ORIGINAL_T_PURCHASE_PRICE,
    basePrice: computeBasePrice(ORIGINAL_T_PURCHASE_PRICE, 'standard'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL'],
    tagline: 'Der budgetfreundliche Favorit für Promotions',
    material: '100% Baumwolle (meliert: 98% Baumwolle, 2% Polyester)',
    weightGsm: 145,
    fit: 'Classic Fit, Unisex',
    description:
      'Das Original ist unser budgetfreundlicher Favorit für Promotions und aus 100% Baumwolle mit einem geringen Stoffgewicht von 140/145 g/m² gefertigt. Die perfekte Wahl für einmalig stattfindende Veranstaltungen und großangelegte Promotions, ohne Kompromisse bei der Qualität.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Unisex/Herren',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Höhere Maschendichte für bessere Bedruckbarkeit',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'Rundhalsausschnitt',
        'Höhere Maschendichte für bessere Bedruckbarkeit',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 46, hoeheCm: 66.5 },
        { size: 'M', breiteCm: 51, hoeheCm: 69 },
        { size: 'L', breiteCm: 56, hoeheCm: 71.5 },
        { size: 'XL', breiteCm: 61, hoeheCm: 74 },
        { size: 'XXL', breiteCm: 66, hoeheCm: 76.5 },
        { size: '3XL', breiteCm: 73, hoeheCm: 79 },
        { size: '4XL', breiteCm: 78, hoeheCm: 80.5 },
        { size: '5XL', breiteCm: 83, hoeheCm: 82 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-original-t', 'white', [
      'navy',
      'solar-yellow',
      'black',
      'bottle-green',
      'red',
      'burgundy',
      'orange',
      'kelly-green',
      'royal',
      'pink',
      'heather-grey',
      'deep-navy',
      'cranberry',
      'graphite',
      'yellow',
      'azure',
          'lime-green',
      'sky-blue',
      'urban-khaki',
]),
  },
  {
    id: 'fotl-ladies-valueweight-t',
    name: 'Ladies Valueweight T',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'basic',
    purchasePrice: LADIES_VALUEWEIGHT_T_PURCHASE_PRICE,
    basePrice: computeBasePrice(LADIES_VALUEWEIGHT_T_PURCHASE_PRICE, 'basic'),
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    tagline: 'Die Damen-Variante unseres unbedruckten T-Shirt-Bestsellers',
    material: '100% Baumwolle (meliert: diverse Baumwoll-/Polyester-Mischungen)',
    weightGsm: 165,
    fit: 'Feminine Passform mit Seitennähten',
    description:
      'Das Ladies Valueweight T kommt im Feminine Fit. Das T-Shirt aus 100% Baumwolle verbindet mit seinem mittleren Stoffgewicht von 160/165 g/m² ein robustes Design mit hohem Komfort für jeden Tag und einer glatten Oberfläche, die zuverlässig perfekte Print-Ergebnisse liefert.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Damen',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Höhere Maschendichte für bessere Bedruckbarkeit',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'Rundhalsausschnitt',
        'Gleichfarbiges Nackenband',
        'Feminine Passform mit Seitennähten',
        'Höhere Maschendichte für bessere Bedruckbarkeit',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
        'Null-Abfall-Produktion: keine Textilabfälle an Deponien',
      ],
    },
    // Powder Blue im Rohmaterial nur mit Front-/Rückansicht vorhanden
    // (keine Seitenansicht) – bewusst ausgelassen, siehe Muster bei
    // anderen Produkten dieser Marke.
    sizeGuide: {
      measurements: [
        { size: 'XS', breiteCm: 41.5, hoeheCm: 62 },
        { size: 'S', breiteCm: 44, hoeheCm: 63 },
        { size: 'M', breiteCm: 46.5, hoeheCm: 64 },
        { size: 'L', breiteCm: 49, hoeheCm: 65 },
        { size: 'XL', breiteCm: 51.5, hoeheCm: 66 },
        { size: 'XXL', breiteCm: 54, hoeheCm: 67 },
      ],
      fitRating: 50,
    },
    colors: realPhotoColorSet('fotl-ladies-valueweight-t', 'azure', [
      'navy',
      'solar-yellow',
      'bottle-green',
      'red',
      'burgundy',
      'orange',
      'royal',
      'pink',
      'deep-navy',
      'graphite',
      'yellow',
      'cranberry',
      'white',
          'blush',
      'heather-charcoal',
      'heather-purple',
      'heather-royal',
      'lime-green',
      'purple',
]),
  },
  {
    id: 'fotl-baseball-t',
    name: 'Baseball T-Shirt',
    brand: 'Fruit of the Loom',
    productType: 'tshirt',
    qualityTier: 'basic',
    purchasePrice: BASEBALL_T_PURCHASE_PRICE,
    basePrice: computeBasePrice(BASEBALL_T_PURCHASE_PRICE, 'basic'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tagline: 'Klassisches Raglan-T-Shirt im Baseball-Look',
    material: '100% Baumwolle',
    weightGsm: 160,
    fit: 'Unisex, normale Passform, Raglanärmel',
    description:
      'Klassisch geschnittenes Baseball-T-Shirt mit kontrastfarbenen Raglanärmeln – der sportliche Klassiker für Freizeit, Team und Vereinskleidung.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 46, hoeheCm: 69 },
        { size: 'M', breiteCm: 49, hoeheCm: 71 },
        { size: 'L', breiteCm: 54, hoeheCm: 74 },
        { size: 'XL', breiteCm: 59, hoeheCm: 76 },
        { size: 'XXL', breiteCm: 64, hoeheCm: 78 },
      ],
      fitRating: 50,
    },
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'T-Shirts',
      gender: 'Unisex',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Klassischer Single-Jersey mit kontrastfarbenen Raglanärmeln (160 g/m²)',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'Kontrastfarbene Raglanärmel',
        'Rundhalsausschnitt mit Ripp-Bündchen',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
      ],
    },
    // Alle 4 Ansichten sind bei jeder Farbe echte, farblich passende Fotos
    // (Spreadshirt-Bildserver, productType=114) – die kontrastfarbenen
    // Raglanärmel sind auf jedem Foto real und farblich korrekt.
    colors: realPhotoColorSet('fotl-baseball-t', 'white-navy', ['white-black', 'white-royal']),
  },
  {
    id: 'fotl-premium-polo',
    name: 'Premium Polo',
    brand: 'Fruit of the Loom',
    productType: 'polo',
    qualityTier: 'standard',
    purchasePrice: PREMIUM_POLO_PURCHASE_PRICE,
    basePrice: computeBasePrice(PREMIUM_POLO_PURCHASE_PRICE, 'standard'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tagline: 'Sportliches Poloshirt in klassischem Piqué',
    material: '100% Baumwolle (Hellgrau meliert: 90%/10% Polyester, Grau meliert: 97%/3% Polyester)',
    weightGsm: 170,
    fit: 'Unisex, gerader Schnitt',
    description:
      'Sportliches, gerade geschnittenes Poloshirt aus strukturiertem Piqué-Stoff mit 3-Knopfleiste und passenden Knöpfen sowie eng anliegendem Ripp-Strick an Ärmeln und Bund – der klassische Bestseller unter den FOTL-Poloshirts.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 48, hoeheCm: 70 },
        { size: 'M', breiteCm: 52, hoeheCm: 72 },
        { size: 'L', breiteCm: 56, hoeheCm: 74 },
        { size: 'XL', breiteCm: 60, hoeheCm: 76 },
        { size: 'XXL', breiteCm: 64, hoeheCm: 78 },
      ],
      fitRating: 50,
    },
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'Poloshirts',
      gender: 'Unisex',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Strukturierter Piqué-Stoff (170 g/m²)',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        '3-Knopfleiste mit passenden Knöpfen',
        'Eng anliegender Ripp-Strick an Ärmeln und Bund',
        'OEKO-TEX STANDARD 100 zertifiziert',
        'Plastikfrei verpackt',
      ],
    },
    // Alle 4 Ansichten sind bei jeder Farbe echte, farblich passende Fotos
    // (Spreadshirt-Bildserver, productType=1523).
    colors: realPhotoColorSet('fotl-premium-polo', 'black', ['navy', 'royal', 'grey', 'white', 'red', 'bottle-green']),
  },
  {
    id: 'fotl-ladies-premium-polo',
    name: 'Premium Polo Lady-Fit',
    brand: 'Fruit of the Loom',
    productType: 'polo',
    qualityTier: 'standard',
    purchasePrice: LADIES_PREMIUM_POLO_PURCHASE_PRICE,
    basePrice: computeBasePrice(LADIES_PREMIUM_POLO_PURCHASE_PRICE, 'standard'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tagline: 'Tailliertes Piqué-Polo für Damen mit 2-Knopfleiste',
    material: '97% Baumwolle, 3% Elastan (Piqué; Grau meliert abweichend)',
    weightGsm: 180,
    fit: 'Damen, taillierter Lady-Fit mit Seitennähten',
    description:
      'Die Damen-Variante des Premium Polos: tailliert geschnittenes Piqué-Poloshirt mit kurzer 2-Knopfleiste, geripptem Kragen und Ärmelbündchen – für Teams, die Herren- und Damen-Passform aus einer Produktlinie kombinieren möchten.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 44, hoeheCm: 64 },
        { size: 'M', breiteCm: 47, hoeheCm: 66 },
        { size: 'L', breiteCm: 50, hoeheCm: 68 },
        { size: 'XL', breiteCm: 53, hoeheCm: 70 },
        { size: 'XXL', breiteCm: 57, hoeheCm: 72 },
      ],
      fitRating: 35,
    },
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'Poloshirts',
      gender: 'Damen',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Piqué-Stoff mit Elastan-Anteil für Formstabilität (180 g/m²)',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'Taillierter Lady-Fit mit Seitennähten',
        'Kurze 2-Knopfleiste mit passenden Knöpfen',
        'Gerippter Kragen und Ärmelbündchen',
        'OEKO-TEX STANDARD 100 zertifiziert',
      ],
    },
    // Alle 4 Ansichten sind bei jeder Farbe echte, farblich passende Fotos
    // (Spreadshirt-Bildserver, productType=1524) – inkl. echter
    // Ärmel-Nahaufnahmen wie beim Herren-Premium-Polo.
    colors: realPhotoColorSet('fotl-ladies-premium-polo', 'black', ['white', 'navy', 'red', 'royal', 'grey', 'burgundy']),
  },
  {
    id: 'fotl-baseball-longsleeve',
    name: 'Baseball Longsleeve',
    brand: 'Fruit of the Loom',
    productType: 'longsleeve',
    qualityTier: 'basic',
    purchasePrice: BASEBALL_LONGSLEEVE_PURCHASE_PRICE,
    basePrice: computeBasePrice(BASEBALL_LONGSLEEVE_PURCHASE_PRICE, 'basic'),
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tagline: 'Langarm-Baseballshirt mit kontrastfarbenen Raglanärmeln',
    material: '100% Baumwolle',
    weightGsm: 160,
    fit: 'Unisex, fällt klein aus, Raglanärmel',
    description:
      'Klassisch geschnittenes Langarm-Baseballshirt mit kontrastfarbenen Raglanärmeln – die Langarm-Variante unseres Baseball-T-Shirts für kühlere Tage.',
    certifications: ['OEKO-TEX Standard 100'],
    careInstructions: '40°C waschbar',
    sizeGuide: {
      measurements: [
        { size: 'S', breiteCm: 45, hoeheCm: 69 },
        { size: 'M', breiteCm: 49, hoeheCm: 71 },
        { size: 'L', breiteCm: 54, hoeheCm: 74 },
        { size: 'XL', breiteCm: 59, hoeheCm: 76 },
        { size: 'XXL', breiteCm: 64, hoeheCm: 78 },
      ],
      fitRating: 25,
    },
    detailedDescription: {
      supplierBrand: 'Fruit of the Loom',
      productType: 'Longsleeves',
      gender: 'Unisex',
      sustainability: 'Plastikfrei verpackt, Null-Abfall-Produktion',
      materialDetail: 'Klassischer Single-Jersey mit kontrastfarbenen Raglanärmeln (160 g/m²)',
      countryOfOrigin: 'k.A.',
      bulletPoints: [
        'Kontrastfarbene Raglanärmel',
        'Langarm für kühlere Tage',
        'Rundhalsausschnitt mit Ripp-Bündchen',
        'OEKO-TEX STANDARD 100 zertifiziert',
      ],
    },
    // Alle 4 Ansichten sind bei jeder Farbe echte, farblich passende Fotos
    // (Spreadshirt-Bildserver, productType=36) – die kontrastfarbenen
    // Raglanärmel sind auf jedem Foto real und farblich korrekt.
    colors: realPhotoColorSet('fotl-baseball-longsleeve', 'white-navy', ['white-black', 'white-royal']),
  },
];
